/Generator/ScintGenerator/region     AD_HOC
/Generator/ScintGenerator/nphotons   1
/Geometry/Next100/specific_vertex_X  0  cm
/Geometry/Next100/specific_vertex_Y  0  cm
/Geometry/Next100/specific_vertex_Z  25 cm
/control/verbose  0
/run/verbose      0
/event/verbose    0
/tracking/verbose 0
/Geometry/Next100/max_step_size     1. mm
/Geometry/Next100/pressure          10.2 bar
/Geometry/Next100/sc_yield          25510. 1/MeV
/Geometry/Next100/drift_transv_diff 1.2 mm/sqrt(cm)
/Geometry/Next100/drift_long_diff   0.3 mm/sqrt(cm)
/Geometry/Next100/e_lifetime        12. ms
/Geometry/Next100/EL_field          12.8 kilovolt/cm
/Geometry/Next100/elfield                        true
/PhysicsList/Nexus/clustering                    true
/PhysicsList/Nexus/drift                         true
/PhysicsList/Nexus/electroluminescence           true
/process/optical/processActivation Cerenkov      true
/process/optical/processActivation Scintillation true
/nexus/random_seed 1
/nexus/persistency/start_id 0
#/nexus/persistency/outputFile out
